###############################################################################
#                                                                             #
#Write Argo BUFR software input and output  from Netcdf                       #
#                                                                             #
###############################################################################
ArgoBufr.inputFolder=..//output//						#input folder where Netcdf files located
ArgoBufr.outputFolder=..//output//									# output folder where the BUFR message will write to
ArgoBufr.outputBufr=..//output//meds.bufr						# name of the BUFR file output.  You can change it to whatever you like
ArgoBufr.BufrTemplate=..//input//ARGOTEMPLATE.csv  	# BUFR template sequences will be used to encode temp, psal, doxy, ph etc
ArgoBufr.failedFtpFile= ..//output//failedFtp.txt
ArgoBufr.bulletinHeader=IOPX02											# GTS bulletin header (You will need to change this to respect your data center !!!)
ArgoBufr.bulletinOrigin=CWOW												# GTS data center code (You will need to change this to respect your data center !!!)
ArgoBufr.originatorCenterId=174											# GTS originator id number (You will need to change this to respect your data center !!!)
ArgoBufr.originatorSubCenterId=0										# GTS originator sub center id (You will need to change this to respect your data center !!!)
ArgoBufr.sendAuxData=true														# set to true if you want to send all data (core + bgc), set to false if you want to send only core data
###############################################################################
